/* eslint-disable */
// This file is auto-generated by TanStack Router
// Do not edit manually

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

import { RootRoute } from './routes/__root'
import { IndexRoute } from './routes/index'
import { LoginRoute } from './routes/login'
import { SignupRoute } from './routes/signup'
import { AcceptInviteRoute } from './routes/accept-invite'
import { DashboardRoute } from './routes/dashboard'
import { ProjectsNewRoute } from './routes/projects.new'
import { ProjectDetailRoute } from './routes/projects.$id'
import { ProjectUploadRoute } from './routes/projects.$id.upload'
import { ProjectSettingsRoute } from './routes/projects.$id.settings'
import { AdminRoute } from './routes/admin'
import { AdminUsersRoute } from './routes/admin.users'

const rootRoute = RootRoute
const indexRoute = IndexRoute
const loginRoute = LoginRoute
const signupRoute = SignupRoute
const acceptInviteRoute = AcceptInviteRoute
const dashboardRoute = DashboardRoute
const projectsNewRoute = ProjectsNewRoute
const projectDetailRoute = ProjectDetailRoute
const projectUploadRoute = ProjectUploadRoute
const projectSettingsRoute = ProjectSettingsRoute
const adminRoute = AdminRoute
const adminUsersRoute = AdminUsersRoute

export const routeTree = rootRoute.addChildren([
  indexRoute,
  loginRoute,
  signupRoute,
  acceptInviteRoute,
  dashboardRoute,
  projectsNewRoute,
  projectDetailRoute,
  projectUploadRoute,
  projectSettingsRoute,
  adminRoute.addChildren([adminUsersRoute]),
])
