/* eslint-disable */
// This file is auto-generated by TanStack Router
// Do not edit manually

import { RootRoute } from './routes/__root'
import { IndexRoute } from './routes/index'
import { LoginRoute } from './routes/login'
import { SignupRoute } from './routes/signup'
import { AcceptInviteRoute } from './routes/accept-invite'
import { DashboardRoute } from './routes/dashboard'
import { ProjectsNewRoute } from './routes/projects.new'
import { ProjectDetailRoute } from './routes/projects.$id'
import { ProjectUploadRoute } from './routes/projects.$id.upload'
import { ProjectSettingsRoute } from './routes/projects.$id.settings'
import { AdminRoute } from './routes/admin'
import { AdminUsersRoute } from './routes/admin.users'

export const routeTree = RootRoute.addChildren([
  IndexRoute,
  LoginRoute,
  SignupRoute,
  AcceptInviteRoute,
  DashboardRoute,
  ProjectsNewRoute,
  ProjectDetailRoute,
  ProjectUploadRoute,
  ProjectSettingsRoute,
  AdminRoute.addChildren([AdminUsersRoute]),
])
